version: '3'
services:
 web: 
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - "3000:3000"
  volumes:
    - .:/apps
 tests:
  build:
   context: .
   dockerfile: Dockerfile.dev
  volumes:
    - .:/apps
  command: ["npm", "run", "test"]